#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export SERVER_PORT="${SERVER_PORT:-8080}"
export DATABASE_URL="${DATABASE_URL:-jdbc:postgresql://localhost:5432/happynovel}"
export DATABASE_USERNAME="${DATABASE_USERNAME:-happynovel}"
export DATABASE_PASSWORD="${DATABASE_PASSWORD:-happynovel}"
export CONTENT_REPOSITORY_MODE="${CONTENT_REPOSITORY_MODE:-JDBC}"
export ADMIN_REPOSITORY_MODE="${ADMIN_REPOSITORY_MODE:-JDBC}"
export AUDIT_REPOSITORY_MODE="${AUDIT_REPOSITORY_MODE:-JDBC}"
export GLOSSARY_REPOSITORY_MODE="${GLOSSARY_REPOSITORY_MODE:-JDBC}"
export PUBLICATION_REPOSITORY_MODE="${PUBLICATION_REPOSITORY_MODE:-JDBC}"
export READING_REPOSITORY_MODE="${READING_REPOSITORY_MODE:-JDBC}"
export CRAWLING_REPOSITORY_MODE="${CRAWLING_REPOSITORY_MODE:-JDBC}"
export ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
export ADMIN_PASSWORD="${ADMIN_PASSWORD:-change-me}"

cd "$ROOT_DIR/backend"
exec ../gradlew bootRun
